## Self practice of numpy

1. Simple array

In [2]:
import numpy as np

In [7]:
simple_array = np.array([1, 5, 4, 3])
print(simple_array)

[1 5 4 3]


1.1 simple array with datatype

In [8]:
dtype_array = np.array([5, 7,9, 8], dtype=float)
print(dtype_array)


[5. 7. 9. 8.]


2. Array with `arange`

In [10]:
arange_array = np.arange(0, 20, 4)
print(arange_array)

[ 0  4  8 12 16]


3. Array with `linspace`

In [11]:
line_array = np.linspace(0, 100, 4, dtype=int)
print(line_array)

[  0  33  66 100]


4. array with `ones`


In [14]:
one_array = np.ones(3)
print(one_array)

# try 2 parameters
print('ones with 2 parameters 3,4')
two_array = np.ones((3, 4), dtype=int)
print(two_array)

[1. 1. 1.]
ones with 2 parameters 3,4
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


5. array with `zero`

In [15]:
zero_arry = np.zeros(4)
print(zero_arry)

[0. 0. 0. 0.]


6. array with `empty`

In [19]:
empty_array = np.empty(5)
print(empty_array)

[0.e+000 2.e-323 4.e-323 6.e-323 8.e-323]


7. array with `random` value

In [3]:
random_arry = np.random.rand(3)
print(random_arry)

[0.78602805 0.57585871 0.65490336]


8. Converting one dimentional array to multidimentional with `reshape`

In [4]:
one_dimen_array = np.array([1, 2, 3, 4, 5 , 6])
multidimen_arry = one_dimen_array.reshape(2, 3)
print(multidimen_arry)

[[1 2 3]
 [4 5 6]]


9. cheking `dimention` `shape` and `size` of array
- `ndim` shows the dimention of the array
- `shape` shows the number of rows and colums in an array
- `size` shows the total number of elements of the array, including sub arrays

In [6]:
print('the dimention of the array:', multidimen_arry.ndim)
print('the shape of the array:', multidimen_arry.shape)
print('the size of the array:', multidimen_arry.size)

the dimention of the array: 2
the shape of the array: (2, 3)
the size of the array: 6


10. Doing math operation on np array (math operation work differently in np array than list of python)

In [7]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

print('addition:', a + b)
print('subtraction:', a - b)
print('multiplication:', a * b)
print('division:', a / b)

addition: [3 6 9]
subtraction: [1 2 3]
multiplication: [ 2  8 18]
division: [2. 2. 2.]


11. **Broadcasting**  allows you to perform operations specifically on arrays of different shapes


In [8]:
mile_array = np.array([1, 2, 3])
km_arrya = mile_array * 1.6

print('km:', km_arrya)


km: [1.6 3.2 4.8]


12. Indexing and slicing one dimentional array

The syntax is:

`array[start:end:step]`

In [9]:
one_dim_array = np.array([1, 2, 3, 4, 5, 6])

print('the first element:', one_dim_array[0])
print('the last element:', one_dim_array[-1])
print('the first 3 elements:', one_dim_array[:3])
print('last elemtent except first three:', one_dim_array[3:])
print('get all with 2 interval:', one_dim_array[::2])

the first element: 1
the last element: 6
the first 3 elements: [1 2 3]
last elemtent except first three: [4 5 6]
get all with 2 interval: [1 3 5]


13. Getting specific indexed element from two dimentional array

In [10]:
two_dime_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('print every second element',two_dime_array[:, 1])

print every second element [2 5 8]


Stacking


In [11]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
print('array 1:', a1)
print('array 2:', a2)

array 1: [[1 1]
 [2 2]]
array 2: [[3 3]
 [4 4]]


14. `np.vstack()` - stacks vertically - you need to pass like tuple within another parenthesis


In [13]:
vertically_stack = np.vstack((a1, a2))
print('vertically stack:', vertically_stack)

vertically stack: [[1 1]
 [2 2]
 [3 3]
 [4 4]]


15. `np.hstack()` - stacks horizontally

In [14]:
horizontally_stack = np.hstack((a1, a2))
print('horizontally stack:', horizontally_stack)

horizontally stack: [[1 1 3 3]
 [2 2 4 4]]


16. `np.hsplit()` - splits an array into several smaller arrays - only 3 worked


In [17]:
array_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_array = np.hsplit(array_to_split, 3)

print('split array:', split_array)

split array: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
