Practice in second round

1. Array with numpy

In [1]:
import numpy as np

1.1 Simple 1 dimensional array with numpy

In [2]:
simple_array = np.array([1, 2, 3])
print('Simple Array :', simple_array)

d_type_array = np.array([3, 5, 7], dtype='float')
print('Array with float numbers', d_type_array)

Simple Array : [1 2 3]
Array with float numbers [3. 5. 7.]


1.2 one dimensional array with arange

In [3]:
range_array = np.arange(5)
print('Range array', range_array)

# arange(start_point, end_point, interval)
interval_range_array = np.arange(1, 10, 2)
print('Interval range array', interval_range_array)

Range array [0 1 2 3 4]
Interval range array [1 3 5 7 9]


1.3 one dimensional array with linespace

In [4]:
# linespace(start, end, number_of_output_evenly_spaced)
simple_linespace = np.linspace(5, 100, 5)
print(simple_linespace)

[  5.    28.75  52.5   76.25 100.  ]


1.4 More types of arrays

In [5]:
#ones
ones = np.ones(5)
print('ones,', ones)

ones, [1. 1. 1. 1. 1.]


In [6]:
zeros = np.zeros(6)
print('zeros', zeros)

zeros [0. 0. 0. 0. 0. 0.]


In [7]:
randoms = np.random.rand(4)
print('randoms', randoms)

randoms [0.00637032 0.82325018 0.18323385 0.60769684]


In [8]:
# it will take the last values of it
empty = np.empty(4)
print('empty array', empty)

empty array [0.00637032 0.82325018 0.18323385 0.60769684]


2. Multi-dimensional array


In [9]:
two_dim_array = np.array([[1, 2, 3], [4, 5, 6]])
print('two dimensional array', two_dim_array)

two dimensional array [[1 2 3]
 [4 5 6]]


2.1 converting one dim array to two dim array

In [10]:
one_dim = np.array([1, 2, 3, 4, 5, 6])
two_dim = one_dim.reshape((2,3))
print('Converted array', two_dim)

Converted array [[1 2 3]
 [4 5 6]]


2.2 Finding shape, size and dimension

In [11]:
# dimension of the array
two_dim.ndim


2

In [12]:
# shape of the array
two_dim.shape

(2, 3)

In [13]:
#size of the array
two_dim.size


6

3. Addition, subtraction, and multiplication in numpy array

In [14]:
even = np.array([2, 4, 6])
odd = np.array([1, 3, 5])

addition = even + odd
print('Addition result ', addition)

subtraction = even - odd
print('Subtraction result', subtraction)

multiplication = even * odd
print('Multiplication result', multiplication)

Addition result  [ 3  7 11]
Subtraction result [1 1 1]
Multiplication result [ 2 12 30]


3.1 Multiplying vector with scaler

In [15]:
vector = np.array([4, 5])
scaler = 1.6
result = vector * scaler

print('1D vector with scaler multiplication', result)

two_d_vector = np.array([[4, 5], [6, 7]])
print('2d vector with scaler multiplicaiton', two_d_vector*scaler)

1D vector with scaler multiplication [6.4 8. ]
2d vector with scaler multiplicaiton [[ 6.4  8. ]
 [ 9.6 11.2]]


4.1 Indexing the array

In [16]:
tow_dim = np.array([[1, 3, 4], [5, 6, 7], [8, 9, 10]])

# accesing the second element of second list
print('second list second element', tow_dim[1][1])

second list second element 6


4.2 slicing the array

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [18]:
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5 6]


In [19]:
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


In [20]:
sliced_arr_1 = b[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
sliced_two_dim_cols = b[:,1]
print(sliced_two_dim_cols)

[2 5 8]


5. Stacking array

In [22]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])

In [24]:
# vertical stacking
vstack = np.vstack((a1, a2))
print(vstack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [25]:
# horizontal stacking
hstack = np.hstack((a1, a2))
print(hstack)

[[1 1 3 3]
 [2 2 4 4]]
