### Matrix multiplication

In [2]:
import numpy as np

A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
B = np.array([[2, 2], [5, 7], [4, 4]])

1. multiplication with matmul

In [6]:
print(np.matmul(A, B))

[[ 89 107]
 [ 47  49]
 [ 40  44]]


2. multiplication with np @

In [7]:
print(A @ B)

[[ 89 107]
 [ 47  49]
 [ 40  44]]


3. multiplication with np dot

In [8]:
print(np.dot(A, B))

[[ 89 107]
 [ 47  49]
 [ 40  44]]


4. dot product with matmul

In [9]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])
print(np.matmul(x, y))

3
